### PR TITLE
webchat package conformity with rasa core 0.12.x

### PR DESCRIPTION
**Pull request by tahesse**
Update `rasa_addons/webchat/__init__.py` to the Rasa Core 0.12.x standards (multi-channel handling through one Flask server)

### CODE REVIEW

**Comment by tahesse** [comment]
This PR can serve as a starting point as I only modified the `rasa_addons/webchat/__init__.py` file.

**Comment by znat** [comment]
Thanks @tahesse , have you considered the new Rasa Core SocketIOInput channel?

**Comment by tahesse** [comment]
Hi @znat, though it doesn't come as single channel with the option for an integrated view. In case you think it is better to combine `SocketIOInput` and `RestInput` in the `handle_channels` method from the agent, I can as well close this PR.

**Comment by znat** [comment]
@tahesse how is the SocketIOInput channel working for you? Can I close this?

**Pull request closed without merging**
